version: '0.1'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
  qdrant_feed:
    build:
      context: ./  # Use the context to specify the build context
      dockerfile: Dockerfile  # Specify the Dockerfile for building the app service
      target: qdrant_feed
    depends_on:
      - qdrant
  app:
    build:
      context: ./  # Use the context to specify the build context
      dockerfile: Dockerfile  # Specify the Dockerfile for building the app service
      target: streamlit_app
    ports:
      - "9090:9090"
    depends_on:
      - qdrant
